const courses={
zh:{name:"中文",flag:"🇨🇳",level:"HSK",badge:"CONVERSATION · 中文",voice:"zh-CN",scenes:[["카페에서 주문하기","원하는 음료와 옵션을 자연스럽게 말해보세요.","你好，你想喝什么？","“아이스 라테 한 잔 주세요”라고 중국어로 말해보세요.","我要一杯冰拿铁。"],["길 묻기","짧고 공손하게 목적지를 물어봅니다.","请问，地铁站怎么走？","“여기서 멀어요?”라고 물어보세요.","离这里远吗？"],["친구와 약속","시간과 장소를 정해봅니다.","你周末有空吗？","“토요일 오후는 어때?”라고 말해보세요.","星期六下午怎么样？"]]},
ja:{name:"日本語",flag:"🇯🇵",level:"JLPT",badge:"CONVERSATION · 日本語",voice:"ja-JP",scenes:[["식당에서 주문하기","추천을 묻고 메뉴를 주문합니다.","ご注文はお決まりですか？","“추천 메뉴는 무엇인가요?”라고 말해보세요.","おすすめは何ですか？"],["역에서 길 찾기","교통 상황에서 필요한 표현을 연습합니다.","どちらまで行かれますか？","“시부야역에 가고 싶어요”라고 말해보세요.","渋谷駅に行きたいです。"],["첫 만남","자연스럽게 자기소개를 이어갑니다.","はじめまして。お名前は？","이름을 말하고 반갑다고 해보세요.","はじめまして。よろしくお願いします。"]]},
de:{name:"Deutsch",flag:"🇩🇪",level:"CEFR",badge:"CONVERSATION · DEUTSCH",voice:"de-DE",scenes:[["카페에서","정중하게 주문하고 결제합니다.","Guten Tag! Was darf es sein?","“카푸치노 한 잔 부탁해요”라고 말해보세요.","Einen Cappuccino, bitte."],["호텔 체크인","예약과 체크인 표현을 연습합니다.","Haben Sie eine Reservierung?","“제 이름으로 예약했습니다”라고 말해보세요.","Ich habe auf meinen Namen reserviert.","Ich habe auf meinen Namen reserviert."],["주말 계획","친구와 가벼운 대화를 이어갑니다.","Was machst du am Wochenende?","“친구들을 만날 거예요”라고 답해보세요.","Ich treffe meine Freunde."]]},
it:{name:"Italiano",flag:"🇮🇹",level:"CEFR",badge:"CONVERSATION · ITALIANO",voice:"it-IT",scenes:[["바에서 주문하기","이탈리아식 카페 상황을 연습합니다.","Buongiorno, cosa prende?","“에스프레소 하나 주세요”라고 말해보세요.","Un espresso, per favore."],["쇼핑하기","가격과 사이즈를 자연스럽게 묻습니다.","Posso aiutarla?","“이거 얼마예요?”라고 물어보세요.","Quanto costa questo?"],["저녁 약속","시간을 정하고 확인합니다.","A che ora ci vediamo?","“7시에 만나요”라고 답해보세요.","Ci vediamo alle sette."]]},
en:{name:"Academic",flag:"🎓",level:"CEFR C1",badge:"ACADEMIC ENGLISH",voice:"en-US",scenes:[["Seminar discussion","State a position with appropriate academic hedging.","How would you interpret these findings?","Start with “The evidence appears to suggest…”","The evidence appears to suggest that context plays a significant role."],["Presentation Q&A","Respond to a challenge clearly and diplomatically.","Could you clarify the limitation of your approach?","Acknowledge the limitation, then explain its scope.","That's an important limitation; however, its impact is restricted to the initial sample."],["Research synthesis","Connect two sources rather than merely summarizing them.","How do these two studies relate?","Use “Taken together, these studies…”","Taken together, these studies indicate a consistent relationship across contexts."]]}
};
let lang=localStorage.lang||"zh",step=+(localStorage.step||0),done=+(localStorage.done||0),reviews=JSON.parse(localStorage.reviews||"[]");const $=id=>document.getElementById(id);let syncTimer=null,syncing=false;
const normalize=s=>s.toLocaleLowerCase().replace(/[.,!?;:'"”“，。？！、\s]/g,"");
function similarity(a,b){a=normalize(a);b=normalize(b);if(!a||!b)return 0;let hit=0;for(const ch of new Set([...b]))if(a.includes(ch))hit++;return Math.round(hit/new Set([...b]).size*100)}
function renderLangs(){$("languages").innerHTML=Object.entries(courses).map(([k,c])=>`<button class="lang ${k===lang?"active":""}" data-lang="${k}"><span>${c.flag}</span>${c.name}<small>${c.level}</small></button>`).join("");document.querySelectorAll(".lang").forEach(b=>b.onclick=()=>{lang=b.dataset.lang;step=0;save();render()})}
function render(){renderLangs();const c=courses[lang],s=c.scenes[step];$("modeBadge").textContent=c.badge;$("lessonTitle").textContent=lang==="en"?"Academic English Lab":"Daily Conversation Loop";$("sceneTitle").textContent=s[0];$("sceneGoal").textContent=s[1];$("prompt").textContent=s[2];$("hint").textContent=s[3];$("progressText").textContent=`${step+1} / ${c.scenes.length}`;$("progressBar").style.width=`${(step+1)/c.scenes.length*100}%`;$("doneCount").textContent=done;$("xp").textContent=done*20;$("reviewCount").textContent=reviews.length;$("feedback").classList.add("hidden");$("transcript").textContent=""}
function state(){return {lang,step,done,reviews,updatedAt:Date.now()}}
function save(){localStorage.lang=lang;localStorage.step=step;localStorage.done=done;localStorage.reviews=JSON.stringify(reviews);localStorage.updatedAt=Date.now();scheduleSync()}
function syncConfig(){return {url:(localStorage.supabaseUrl||"").replace(/\/$/,""),key:localStorage.supabaseKey||"",token:localStorage.syncToken||""}}
function syncReady(){const c=syncConfig();return c.url&&c.key&&c.token}
function setSyncStatus(t){const el=$("syncStatus");if(el)el.textContent=t}
function scheduleSync(){if(!syncReady())return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>pushCloud(),700)}
async function tokenHash(token){const bytes=new TextEncoder().encode(token),hash=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function cloudHeaders(){const c=syncConfig();return {apikey:c.key,Authorization:"Bearer "+c.key,"Content-Type":"application/json",Prefer:"return=representation","x-sync-token":c.token}}
async function cloudRequest(method,body){const c=syncConfig(),id=await tokenHash(c.token),url=c.url+"/rest/v1/lingualoop_state?id=eq."+id;const r=await fetch(url,{method,headers:await cloudHeaders(),body:body?JSON.stringify(body):undefined});if(!r.ok)throw new Error(await r.text());return r.status===204?[]:await r.json()}
async function pushCloud(){if(!syncReady()||syncing)return;syncing=true;setSyncStatus("동기화 중…");try{const c=syncConfig(),payload={id:await tokenHash(c.token),state:state(),updated_at:new Date().toISOString()};const rows=await cloudRequest("GET");if(rows.length)await cloudRequest("PATCH",{state:payload.state,updated_at:payload.updated_at});else{const r=await fetch(c.url+"/rest/v1/lingualoop_state",{method:"POST",headers:{...(await cloudHeaders()),Prefer:"return=minimal"},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text())}setSyncStatus("✓ 동기화됨")}catch(e){console.error(e);setSyncStatus("오프라인 · 로컬 저장됨")}finally{syncing=false}}
async function pullCloud(){if(!syncReady())return;setSyncStatus("불러오는 중…");try{const rows=await cloudRequest("GET");if(rows.length&&rows[0].state){const s=rows[0].state;lang=s.lang||lang;step=Number.isFinite(s.step)?s.step:step;done=Number.isFinite(s.done)?s.done:done;reviews=Array.isArray(s.reviews)?s.reviews:reviews;localStorage.lang=lang;localStorage.step=step;localStorage.done=done;localStorage.reviews=JSON.stringify(reviews);render()}else await pushCloud();setSyncStatus("✓ 동기화됨")}catch(e){console.error(e);setSyncStatus("동기화 실패")}}
function openSync(){const c=syncConfig();$("syncUrl").value=c.url;$("syncKey").value=c.key;$("syncToken").value=c.token;$("syncPanel").classList.remove("hidden")}
function saveSync(){localStorage.supabaseUrl=$("syncUrl").value.trim();localStorage.supabaseKey=$("syncKey").value.trim();localStorage.syncToken=$("syncToken").value.trim();$("syncPanel").classList.add("hidden");pullCloud()}
function addReview(text,score=0){const found=reviews.find(x=>x.text===text);if(found){found.lapses=(found.lapses||0)+1;found.lastScore=score;found.due=Date.now()}else reviews.push({lang,text,due:Date.now(),interval:1,lapses:1,lastScore:score});save()}
function dueReviews(){return reviews.filter(x=>x.due<=Date.now()).sort((a,b)=>(b.lapses||0)-(a.lapses||0)||a.due-b.due)}
function gradeReview(x,grade){if(grade==="again"){x.lapses=(x.lapses||0)+1;x.interval=1;x.due=Date.now()+600000}else if(grade==="hard"){x.interval=Math.max(1,Math.round((x.interval||1)*1.5));x.due=Date.now()+x.interval*86400000}else{x.interval=Math.max(2,Math.round((x.interval||1)*2.5));x.due=Date.now()+x.interval*86400000}save();render()}
$("nextBtn").onclick=()=>{done++;step=(step+1)%courses[lang].scenes.length;save();render()};$("prevBtn").onclick=()=>{step=(step-1+courses[lang].scenes.length)%courses[lang].scenes.length;save();render()};
$("speakBtn").onclick=()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(courses[lang].scenes[step][2]);u.lang=courses[lang].voice;speechSynthesis.speak(u)};
$("micBtn").onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$("transcript").textContent="이 브라우저에서는 음성 인식을 지원하지 않습니다.";return}const r=new SR();r.lang=courses[lang].voice;r.interimResults=false;$("transcript").textContent="듣는 중…";r.onresult=e=>{const t=e.results[0][0].transcript,target=courses[lang].scenes[step][4],score=similarity(t,target);$("transcript").textContent="“"+t+"”";const f=$("feedback");f.innerHTML=`<b>${score>=75?"✓ 자연스러운 응답이에요":score>=45?"△ 거의 다 왔어요":"↻ 한 번 더 말해보세요"} · ${score}%</b><br>모델 표현: ${target}<br><small>브라우저 음성인식 결과를 바탕으로 한 간단한 유사도 피드백입니다.</small>`;f.classList.remove("hidden");if(score<75)addReview(target,score);$("reviewCount").textContent=reviews.length};r.onerror=()=>{$("transcript").textContent="음성을 인식하지 못했어요. 다시 시도해 주세요."};r.start()};
$("reviewBtn").onclick=()=>{const due=dueReviews();if(!reviews.length){$("feedback").innerHTML="<b>복습할 표현이 아직 없어요.</b><br>말하기에서 어려웠던 표현이 자동으로 저장됩니다.";$("feedback").classList.remove("hidden");return}const x=due[0]||reviews.slice().sort((a,b)=>(b.lapses||0)-(a.lapses||0))[0];const status=due.length?"오늘 복습할 표현 "+due.length+"개":"오늘 예정된 복습은 끝났어요. 가장 어려운 표현을 다시 봅니다.";$("feedback").innerHTML="<b>약점 복습 · 틀린 횟수 "+(x.lapses||1)+"회</b><br><span class=\"reviewPhrase\">"+x.text+"</span><br><small>"+status+"</small><br><button id=\"reviewSpeak\" class=\"ghost mini\">🔊 듣기</button><div class=\"reviewGrades\"><button id=\"again\" class=\"ghost mini\">다시 · 10분</button><button id=\"hard\" class=\"ghost mini\">어려움</button><button id=\"good\" class=\"primary mini\">기억남</button></div>";$("feedback").classList.remove("hidden");$("reviewSpeak").onclick=()=>{const u=new SpeechSynthesisUtterance(x.text);u.lang=courses[x.lang].voice;speechSynthesis.speak(u)};$("again").onclick=()=>gradeReview(x,"again");$("hard").onclick=()=>gradeReview(x,"hard");$("good").onclick=()=>gradeReview(x,"good")};
$("syncBtn").onclick=openSync;
$("syncSave").onclick=saveSync;
$("syncCancel").onclick=()=>$("syncPanel").classList.add("hidden");
render();
if(syncReady())pullCloud();