import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const cors={"Access-Control-Allow-Origin":"https://kinnwestzero.github.io","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-sync-token","Access-Control-Allow-Methods":"POST, OPTIONS"};
const hex=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,"0")).join("");
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 if(req.method!=="POST")return new Response("Method not allowed",{status:405,headers:cors});
 const token=req.headers.get("x-sync-token")||""; if(token.length<24)return Response.json({error:"unauthorized"},{status:401,headers:cors});
 const id=await hex(token), url=Deno.env.get("SUPABASE_URL")!, service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, openai=Deno.env.get("OPENAI_API_KEY");
 if(!openai)return Response.json({error:"AI is not configured"},{status:503,headers:cors});
 const auth={apikey:service,Authorization:"Bearer "+service,"Content-Type":"application/json"};
 const state=await fetch(url+"/rest/v1/lingualoop_state?id=eq."+id+"&select=id",{headers:auth});
 if(!state.ok)return Response.json({error:"state lookup failed"},{status:502,headers:cors});
 const rows=await state.json(); if(!Array.isArray(rows)||!rows.length)return Response.json({error:"sync profile not found"},{status:401,headers:cors});
 const body=await req.json(), mode=body.mode==="correct"?"correct":body.mode==="meaning"?"meaning":body.mode==="expression"?"expression":"chat", language=body.lang||"en", text=String(body.text||"").slice(0,2000), history=Array.isArray(body.history)?body.history.slice(-8):[], roleplay=!!body.roleplay;
 const system=mode==="expression"?"You help a Korean-speaking learner understand a word or phrase they just encountered and decide when they can naturally use it. Correct a likely misspelling when the context makes the intended expression clear. If it is genuinely ambiguous, choose the most likely expression and mention the uncertainty in NOTE. Give concrete usage facts, not vague advice. Do not invent restrictions: when an expression is common across regions or settings, say so clearly. Keep every explanation in Korean and every target-language example fully separate from its Korean translation. Return exactly these eleven labeled sections in this order. TARGET: corrected target-language word or phrase only, with no Korean. KOREAN: concise Korean meaning only. PRONUNCIATION: IPA or a simple Korean pronunciation guide. REGISTER: one concrete description such as 매우 격식적, 중립적, 일상적, 속어. REGION: where it is used; say 지역 제한 없이 널리 쓰임 when appropriate. CHANNEL: spoken, written, text message, news/media, or professional usage, including which is most common. FREQUENCY: how often a native speaker is likely to encounter it. SITUATION: 2 or 3 concrete real-life situations where it sounds natural. NOTE: nuance, possible negative or humorous tone, and one case where the learner should avoid it. EXAMPLES: exactly 3 natural target-language sentences, one per line, each formatted sentence :: Korean translation. RELATED: exactly 3 related target-language expressions, one per line, each formatted expression :: Korean nuance difference. Never put a Korean translation on the TARGET or left side of EXAMPLES.":mode==="meaning"?"Translate the learner's target-language sentence naturally into Korean. Return exactly: TARGET: followed by the original sentence; KOREAN: followed only by the Korean meaning.":mode==="correct"?"You are LinguaLoop, a concise language coach. Correct the learner's wording. Return exactly two sections: TARGET: followed only by the corrected target-language sentence; KOREAN: followed by one short Korean explanation. For Academic English, prioritize academic register.":roleplay?"You are LinguaLoop in an ongoing roleplay for a beginner learner. Stay in character and end with one short target-language question. Evaluate the learner\'s latest reply gently and concretely. Return exactly four sections: TARGET: only what the roleplay partner says next; KOREAN: concise Korean meaning of TARGET; SUGGESTION: one short natural target-language answer the learner could use next, followed by its Korean meaning in parentheses; FEEDBACK: a very short Korean note on the learner\'s latest answer, saying what was good and one improvement. On the first turn, FEEDBACK may say 시작해볼게요.":"You are LinguaLoop, a concise language coach. Answer the learner's question or help with wording. Return exactly two sections: TARGET: followed by the useful target-language answer/example; KOREAN: followed by one short Korean explanation.";
 const ai=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":"Bearer "+openai,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",input:[{role:"system",content:system+" Target language code: "+language+". Scene: "+String(body.context||"")},...history.map((x:any)=>({role:x.role==="assistant"?"assistant":"user",content:String(x.content||"").slice(0,2000)})),{role:"user",content:text}],reasoning:{effort:"none"},max_output_tokens:800})});
 const data=await ai.json(); if(data?.status==="incomplete"){console.error("OpenAI incomplete",data?.incomplete_details,data?.usage);return Response.json({error:"OpenAI response incomplete: "+String(data?.incomplete_details?.reason||"unknown")},{status:502,headers:cors})} if(!ai.ok)return Response.json({error:"AI provider error"},{status:502,headers:cors});
 const reply=data.output_text||data.output?.flatMap((x:any)=>x.content||[]).filter((x:any)=>x.type==="output_text"||typeof x.text==="string").map((x:any)=>x.text||"").join("\n").trim()||"";
 if(!reply){console.error("Empty OpenAI response",JSON.stringify(data));return Response.json({error:"OpenAI returned an empty response"},{status:502,headers:cors});}
 if(mode==="expression"){
  const em=reply.match(/^TARGET:\s*([\s\S]*?)\s*KOREAN:\s*([\s\S]*?)\s*PRONUNCIATION:\s*([\s\S]*?)\s*REGISTER:\s*([\s\S]*?)\s*REGION:\s*([\s\S]*?)\s*CHANNEL:\s*([\s\S]*?)\s*FREQUENCY:\s*([\s\S]*?)\s*SITUATION:\s*([\s\S]*?)\s*NOTE:\s*([\s\S]*?)\s*EXAMPLES:\s*([\s\S]*?)\s*RELATED:\s*([\s\S]*)$/i);
  if(!em)return Response.json({error:"expression response format failed"},{status:502,headers:cors});
  const pair=(line:string)=>{const [text,...meaning]=line.split("::");return {text:text.trim(),meaning:meaning.join("::").trim()}};
  const examples=em[10].split("\n").map((x:string)=>x.replace(/^[-•\d.)\s]+/,"").trim()).filter((x:string)=>x.includes("::")).map(pair).slice(0,3), related=em[11].split("\n").map((x:string)=>x.replace(/^[-•\d.)\s]+/,"").trim()).filter((x:string)=>x.includes("::")).map(pair).slice(0,3);
  if(examples.length<3)return Response.json({error:"expression examples format failed"},{status:502,headers:cors});
  return Response.json({reply,target:em[1].trim(),korean:em[2].trim(),pronunciation:em[3].trim(),usage:{register:em[4].trim(),region:em[5].trim(),channel:em[6].trim(),frequency:em[7].trim(),situation:em[8].trim()},note:em[9].trim(),examples,related,language},{headers:{...cors,"Content-Type":"application/json"}});
 }
 const rm=roleplay?reply.match(/^TARGET:\s*([\s\S]*?)\s*KOREAN:\s*([\s\S]*?)\s*SUGGESTION:\s*([\s\S]*?)\s*FEEDBACK:\s*([\s\S]*)$/i):null, m=!roleplay?reply.match(/^TARGET:\s*([\s\S]*?)\s*KOREAN:\s*([\s\S]*)$/i):null, target=(rm?.[1]||m?.[1]||reply).trim(), korean=(rm?.[2]||m?.[2]||"").trim(), suggestion=(rm?.[3]||"").trim(), feedback=(rm?.[4]||"").trim();
 return Response.json({reply,target,korean,suggestion,feedback},{headers:{...cors,"Content-Type":"application/json"}});
});
