import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const cors={"Access-Control-Allow-Origin":"https://kinnwestzero.github.io","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-sync-token","Access-Control-Allow-Methods":"POST, OPTIONS"};
const hex=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,"0")).join("");
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 if(req.method!=="POST")return new Response("Method not allowed",{status:405,headers:cors});
 const token=req.headers.get("x-sync-token")||""; if(token.length<24)return Response.json({error:"unauthorized"},{status:401,headers:cors});
 const id=await hex(token), url=Deno.env.get("SUPABASE_URL")!, service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, openai=Deno.env.get("OPENAI_API_KEY");
 if(!openai)return Response.json({error:"AI is not configured"},{status:503,headers:cors});
 const auth={apikey:service,Authorization:"Bearer "+service,"Content-Type":"application/json"};
 const state=await fetch(url+"/rest/v1/lingualoop_state?id=eq."+id+"&select=id",{headers:auth});
 if(!state.ok)return Response.json({error:"state lookup failed"},{status:502,headers:cors});
 const rows=await state.json(); if(!Array.isArray(rows)||!rows.length)return Response.json({error:"sync profile not found"},{status:401,headers:cors});
 const body=await req.json(), mode=body.mode==="correct"?"correct":body.mode==="meaning"?"meaning":"chat", language=body.lang||"en", text=String(body.text||"").slice(0,2000), history=Array.isArray(body.history)?body.history.slice(-8):[], roleplay=!!body.roleplay;
 const system=mode==="meaning"?"Translate the learner's target-language sentence naturally into Korean. Return exactly: TARGET: followed by the original sentence; KOREAN: followed only by the Korean meaning.":mode==="correct"?"You are LinguaLoop, a concise language coach. Correct the learner's wording. Return exactly two sections: TARGET: followed only by the corrected target-language sentence; KOREAN: followed by one short Korean explanation. For Academic English, prioritize academic register.":roleplay?"You are LinguaLoop in an ongoing roleplay for a beginner learner. Stay in character and end with one short target-language question. Evaluate the learner\'s latest reply gently and concretely. Return exactly four sections: TARGET: only what the roleplay partner says next; KOREAN: concise Korean meaning of TARGET; SUGGESTION: one short natural target-language answer the learner could use next, followed by its Korean meaning in parentheses; FEEDBACK: a very short Korean note on the learner\'s latest answer, saying what was good and one improvement. On the first turn, FEEDBACK may say 시작해볼게요.":"You are LinguaLoop, a concise language coach. Answer the learner's question or help with wording. Return exactly two sections: TARGET: followed by the useful target-language answer/example; KOREAN: followed by one short Korean explanation.";
 const ai=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":"Bearer "+openai,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",input:[{role:"system",content:system+" Target language code: "+language+". Scene: "+String(body.context||"")},...history.map((x:any)=>({role:x.role==="assistant"?"assistant":"user",content:String(x.content||"").slice(0,2000)})),{role:"user",content:text}],reasoning:{effort:"none"},max_output_tokens:800})});
 const data=await ai.json(); if(data?.status==="incomplete"){console.error("OpenAI incomplete",data?.incomplete_details,data?.usage);return Response.json({error:"OpenAI response incomplete: "+String(data?.incomplete_details?.reason||"unknown")},{status:502,headers:cors})} if(!ai.ok)return Response.json({error:"AI provider error"},{status:502,headers:cors});
 const reply=data.output_text||data.output?.flatMap((x:any)=>x.content||[]).filter((x:any)=>x.type==="output_text"||typeof x.text==="string").map((x:any)=>x.text||"").join("\n").trim()||"";
 if(!reply){console.error("Empty OpenAI response",JSON.stringify(data));return Response.json({error:"OpenAI returned an empty response"},{status:502,headers:cors});}
 const rm=roleplay?reply.match(/^TARGET:\s*([\s\S]*?)\s*KOREAN:\s*([\s\S]*?)\s*SUGGESTION:\s*([\s\S]*?)\s*FEEDBACK:\s*([\s\S]*)$/i):null, m=!roleplay?reply.match(/^TARGET:\s*([\s\S]*?)\s*KOREAN:\s*([\s\S]*)$/i):null, target=(rm?.[1]||m?.[1]||reply).trim(), korean=(rm?.[2]||m?.[2]||"").trim(), suggestion=(rm?.[3]||"").trim(), feedback=(rm?.[4]||"").trim();
 return Response.json({reply,target,korean,suggestion,feedback},{headers:{...cors,"Content-Type":"application/json"}});
});